Traceback (most recent call last):
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import ROOT
import os
from typing import List
import argparse
import numpy as np
from utils import remove_all_whitespace
from plotgen_utils import book_histogram, turn_on_specifc_waveset
import atiSetup

REPO_HOME     = os.environ['REPO_HOME']
atiSetup.setup(globals(), use_fsroot=True)

from PlotGenRDF import draw_histograms
------------------

----- stdout -----
Welcome to JupyROOT 6.28/06
atiSetup| jupyter-book called python3.9

------------------------------------------------
atiSetup| MPI is disabled
atiSetup| GPU is disabled
------------------------------------------------


atiSetup| Loading library libAmpTools.so ..............  NOT FOUND, SKIPPING
atiSetup| Loading library libAmpPlotter.so ............  NOT FOUND, SKIPPING
atiSetup| Loading library libAmpsDataIO.so ............  NOT FOUND, SKIPPING
atiSetup| Loading library libFSRoot.so ................  NOT FOUND, SKIPPING
atiSetup| Loading library libAmpsGen.so ...............  OFF


------------------------------------------------
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[1], line 11[0m
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01matiSetup[39;00m
[1;32m     10[0m REPO_HOME     [38;5;241m=[39m os[38;5;241m.[39menviron[[38;5;124m'[39m[38;5;124mREPO_HOME[39m[38;5;124m'[39m]
[0;32m---> 11[0m [43matiSetup[49m[38;5;241;43m.[39;49m[43msetup[49m[43m([49m[38;5;28;43mglobals[39;49m[43m([49m[43m)[49m[43m,[49m[43m [49m[43muse_fsroot[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01mPlotGenRDF[39;00m [38;5;28;01mimport[39;00m draw_histograms

File [0;32m/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/atiSetup.py:26[0m, in [0;36msetup[0;34m(calling_globals, accelerator, use_fsroot, use_genamp)[0m
[1;32m     16[0m [38;5;28;01mdef[39;00m [38;5;21msetup[39m(calling_globals, accelerator[38;5;241m=[39m[38;5;124m'[39m[38;5;124mmpigpu[39m[38;5;124m'[39m, use_fsroot[38;5;241m=[39m[38;5;28;01mFalse[39;00m, use_genamp[38;5;241m=[39m[38;5;28;01mFalse[39;00m):
[1;32m     17[0m [38;5;250m    [39m[38;5;124;03m'''[39;00m
[1;32m     18[0m [38;5;124;03m    Performs basic setup, loading libraries and setting aliases[39;00m
[1;32m     19[0m 
[0;32m   (...)[0m
[1;32m     24[0m [38;5;124;03m        use_genamp (bool): True if GenAmp library should be loaded[39;00m
[1;32m     25[0m [38;5;124;03m    '''[39;00m
[0;32m---> 26[0m     USE_MPI, USE_GPU, RANK_MPI [38;5;241m=[39m [43mloadLibraries[49m[43m([49m[43m [49m[43maccelerator[49m[43m,[49m[43m [49m[43muse_fsroot[49m[43m,[49m[43m [49m[43muse_genamp[49m[43m [49m[43m)[49m
[1;32m     27[0m     set_aliases( calling_globals, USE_MPI, USE_GPU )
[1;32m     29[0m     [38;5;28;01mreturn[39;00m USE_MPI, USE_GPU, RANK_MPI

File [0;32m/w/halld-scshelf2101/lng/Mambaforge/envs/PyAmpTools/lib/python3.9/site-packages/atiSetup.py:54[0m, in [0;36mloadLibraries[0;34m(accelerator, use_fsroot, use_genamp)[0m
[1;32m     50[0m [38;5;66;03m# Dummy functions that just prints "initialization"[39;00m
[1;32m     51[0m [38;5;66;03m#  This is to make sure the libraries are loaded[39;00m
[1;32m     52[0m [38;5;66;03m#  as python is interpreted.[39;00m
[1;32m     53[0m [38;5;28;01mif[39;00m RANK_MPI [38;5;241m==[39m [38;5;241m0[39m: [38;5;28mprint[39m([38;5;124m"[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m------------------------------------------------[39m[38;5;124m"[39m)
[0;32m---> 54[0m [43mROOT[49m[38;5;241;43m.[39;49m[43minitialize[49m( RANK_MPI [38;5;241m==[39m [38;5;241m0[39m )
[1;32m     55[0m [38;5;28;01mif[39;00m use_fsroot: ROOT[38;5;241m.[39minitialize_fsroot( RANK_MPI [38;5;241m==[39m [38;5;241m0[39m )
[1;32m     56[0m [38;5;28;01mif[39;00m RANK_MPI [38;5;241m==[39m [38;5;241m0[39m: [38;5;28mprint[39m([38;5;124m"[39m[38;5;124m------------------------------------------------[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m)

File [0;32m~/WORK/WORK/PyAmpTools/root/root-6.28.06-gcc9.3.0/lib/ROOT/_facade.py:196[0m, in [0;36mROOTFacade._fallback_getattr[0;34m(self, name)[0m
[1;32m    194[0m     [38;5;28;01mif[39;00m res:
[1;32m    195[0m         [38;5;28;01mreturn[39;00m res
[0;32m--> 196[0m [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124m"[39m[38;5;124mFailed to get attribute [39m[38;5;132;01m{}[39;00m[38;5;124m from ROOT[39m[38;5;124m"[39m[38;5;241m.[39mformat(name))

[0;31mAttributeError[0m: Failed to get attribute initialize from ROOT

