Traceback (most recent call last):
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
############## SET ENVIRONMENT VARIABLES ##############
PYAMPTOOLS_HOME = os.environ["PYAMPTOOLS_HOME"]
USE_MPI, USE_GPU, RANK_MPI = atiSetup.setup(globals())

cfgfile = f"{PYAMPTOOLS_HOME}/tests/samples/SIMPLE_EXAMPLE/fitInit.cfg"
randomSeed = int(time.time())
seedfile = "seed_file"
numRnd = 0
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m############## SET ENVIRONMENT VARIABLES ##############[39;00m
[0;32m----> 2[0m PYAMPTOOLS_HOME [38;5;241m=[39m [43mos[49m[38;5;241;43m.[39;49m[43menviron[49m[43m[[49m[38;5;124;43m"[39;49m[38;5;124;43mPYAMPTOOLS_HOME[39;49m[38;5;124;43m"[39;49m[43m][49m
[1;32m      3[0m USE_MPI, USE_GPU, RANK_MPI [38;5;241m=[39m atiSetup[38;5;241m.[39msetup([38;5;28mglobals[39m())
[1;32m      5[0m cfgfile [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mPYAMPTOOLS_HOME[38;5;132;01m}[39;00m[38;5;124m/tests/samples/SIMPLE_EXAMPLE/fitInit.cfg[39m[38;5;124m"[39m

File [0;32m/w/halld-scshelf2101/lng/micromamba/envs/pyamptools/lib/python3.9/os.py:679[0m, in [0;36m_Environ.__getitem__[0;34m(self, key)[0m
[1;32m    676[0m     value [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_data[[38;5;28mself[39m[38;5;241m.[39mencodekey(key)]
[1;32m    677[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m:
[1;32m    678[0m     [38;5;66;03m# raise KeyError with the original key value[39;00m
[0;32m--> 679[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;28;01mNone[39;00m
[1;32m    680[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39mdecodevalue(value)

[0;31mKeyError[0m: 'PYAMPTOOLS_HOME'

